version: "3"
services:
    web:                
        build: .            
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
            - ASPNETCORE_Kestrel__Certificates__Default__Path=conf.d/https/dev_cert.pfx
        ports:
            - "8088:80"
            - "8443:443"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "22243:1433"